CREATE TABLE DEPARTMENT
(
    ID bigint PRIMARY KEY NOT NULL,
    NAME varchar(100) NOT NULL,
    ADRESS varchar(100)
);
CREATE TABLE PERSON
(
    ID bigint PRIMARY KEY NOT NULL,
    POSITION_ID bigint NOT NULL,
    FULLNAME varchar(100) NOT NULL,
    DEPARTMENT_ID bigint NOT NULL,
    SALARY bigint NOT NULL
);
CREATE TABLE POSITION
(
    ID bigint PRIMARY KEY NOT NULL,
    NAME varchar(100) NOT NULL
)
CREATE TABLE DEPARTMENT
(
    ID bigint PRIMARY KEY NOT NULL,
    NAME varchar(100) NOT NULL,
    ADRESS varchar(100)
);
CREATE TABLE PERSON
(
    ID bigint PRIMARY KEY NOT NULL,
    POSITION_ID bigint NOT NULL,
    FULLNAME varchar(100) NOT NULL,
    DEPARTMENT_ID bigint NOT NULL,
    SALARY bigint NOT NULL
);
CREATE TABLE POSITION
(
    ID bigint PRIMARY KEY NOT NULL,
    NAME varchar(100) NOT NULL
)
